/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __arm_math_dsp_FFT__H
#define __arm_math_dsp_FFT__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_arm_math_dsp_FFT(Args *args);

void arm_math_dsp_FFT___init__(PikaObj *self);
PikaObj* arm_math_dsp_FFT_rfft(PikaObj *self, PikaObj* inputList, int length);

#endif
