/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __ZeptoWatchStdLib_Clock__H
#define __ZeptoWatchStdLib_Clock__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_ZeptoWatchStdLib_Clock(Args *args);

int ZeptoWatchStdLib_Clock_getDay(PikaObj *self);
int ZeptoWatchStdLib_Clock_getHours(PikaObj *self);
int ZeptoWatchStdLib_Clock_getMinutes(PikaObj *self);
int ZeptoWatchStdLib_Clock_getMonth(PikaObj *self);
int ZeptoWatchStdLib_Clock_getSeconds(PikaObj *self);
int ZeptoWatchStdLib_Clock_getSubseconds(PikaObj *self);
int ZeptoWatchStdLib_Clock_getWeekDay(PikaObj *self);
int ZeptoWatchStdLib_Clock_getYear(PikaObj *self);
void ZeptoWatchStdLib_Clock_setHours(PikaObj *self, int val);
void ZeptoWatchStdLib_Clock_setMinutes(PikaObj *self, int val);
void ZeptoWatchStdLib_Clock_setSeconds(PikaObj *self, int val);
void ZeptoWatchStdLib_Clock_setTime(PikaObj *self, int h, int m, int s);

#endif
