/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __ZeptoWatchPeriphLib_Vibrator__H
#define __ZeptoWatchPeriphLib_Vibrator__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_ZeptoWatchPeriphLib_Vibrator(Args *args);

void ZeptoWatchPeriphLib_Vibrator_stop(PikaObj *self);
void ZeptoWatchPeriphLib_Vibrator_vibrate(PikaObj *self, int ms, int pulse);

#endif
