class IMU:
    def initialize(self): ...
    def getTemperature(self) -> int: ...
    def getGyroscope(self) -> list: ...
    def getAccelerometer(self) -> list: ...


class Battery:
    def isCharging(self) -> int: ...
    def getRawData(self) -> int: ...


class Microphone:
    def startSampling(self): ...
    def stopSampling(self): ...
    def getRawData(self) -> int: ...


class Vibrator:
    def vibrate(self, ms: int, pulse: int): ...
    def stop(self): ...

