class System:
    def delayMs(self, time: int): ...
    def delayMsBlocking(self, time:int): ...
    def delayUsBlocking(self, time:int): ...


class Display:
    def getField(self) -> lv_obj: ...
    def lvglUpdate(self): ...
    def setBrightness(self, val: int): ...
    def getBrightness(self) -> int: ...


class Clock:
    def getHours(self) -> int: ...
    def getMinutes(self) -> int: ...
    def getSeconds(self) -> int: ...
    def getSubseconds(self) -> int: ...
    def getYear(self) -> int: ...
    def getMonth(self) -> int: ...
    def getDay(self) -> int: ...
    def getWeekDay(self) -> int: ...
    def setHours(self, val: int): ...
    def setMinutes(self, val: int): ...
    def setSeconds(self, val: int): ...
    def setTime(self, h: int, m: int, s: int):

