class System:
    def delayMs(self, time: int): ...


class Display:
    def getField(self) -> lv_obj: ...
    def setBrightness(self, val: int): ...
    def getBrightness(self) -> int: ...


class Clock:
    def getHours(self) -> int: ...
    def getMinutes(self) -> int: ...
    def getSeconds(self) -> int: ...
    def getYear(self) -> int: ...
    def getMonth(self) -> int: ...
    def getDay(self) -> int: ...
    def getWeekDay(self) -> int: ...

